Copy_btn_dark_setStyleSheet = ("QPushButton#Copy_btn{\n"
                                        "    color: white;\n"
                                        "    border:3px solid white;\n"
                                        "    border-radius:30px;\n"
                                        "}\n"
                                        "QPushButton#Copy_btn:pressed{\n"
                                        "    color: white;\n"
                                        "    border:3px solid white;\n"
                                        "    border-radius: 30px;\n"
                                        "}")

password_area_dark_setStyleSheet = ("QLineEdit#password_area{\n"
                                             "    \n"
                                             "    color: rgb(60, 252, 255);\n"
                                             "    border: 3px solid rgb(11, 255, 7);\n"
                                             "    border-radius: 35px;\n"
                                             "    background-color: transparent;\n"
                                             "}")

Exit_btn_dark_setStyleSheet = ("QPushButton#Exit_btn{\n"
                                        "    color: white;\n"
                                        "    border:2px solid white;\n"
                                        "    border-radius: 15px;\n"
                                        "    background-color: transparent;\n"
                                        "}\n"
                                        "QPushButton#Exit_btn:pressed{\n"
                                        "    color: red;\n"
                                        "    border:2px solid red;\n"
                                        "    background-color: transparent;\n"
                                        "}")

Language_Btn_dark_setStyleSheet = ("QPushButton#Language_Btn{\n"
                                            "    color: white;\n"
                                            "    border:2px solid white;\n"
                                            "    border-radius: 15px;\n"
                                            "}\n"
                                            "QPushButton#Language_Btn:pressed{\n"
                                            "    color: black;\n"
                                            "    border:2px solid black;\n"
                                            "    border-radius: 15px;\n"
                                            "}")

Copy_btn_light_setStyleSheet = ("QPushButton#Copy_btn{\n"
                                        "    color: black;\n"
                                        "    border:3px solid black;\n"
                                        "    border-radius:30px;\n"
                                        "}\n"
                                        "QPushButton#Copy_btn:pressed{\n"
                                        "    color: white;\n"
                                        "    border:3px solid white;\n"
                                        "    border-radius: 30px;\n"
                                        "}")

password_area_light_setStyleSheet = ("QLineEdit#password_area{\n"
                                             "    \n"
                                             "    color: rgb(60, 252, 255);\n"
                                             "    border: 3px solid rgb(11, 255, 7);\n"
                                             "    border-radius: 35px;\n"
                                             "    background-color: transparent;\n"
                                             "}")

Exit_btn_light_setStyleSheet = ("QPushButton#Exit_btn{\n"
                                        "    color: black;\n"
                                        "    border:2px solid black;\n"
                                        "    border-radius: 15px;\n"
                                        "    background-color: transparent;\n"
                                        "}\n"
                                        "QPushButton#Exit_btn:pressed{\n"
                                        "    color: red;\n"
                                        "    border:2px solid red;\n"
                                        "    background-color: transparent;\n"
                                        "}")

Language_Btn_light_setStyleSheet = ("QPushButton#Language_Btn{\n"
                                            "    color: black;\n"
                                            "    border:2px solid black;\n"
                                            "    border-radius: 15px;\n"
                                            "}\n"
                                            "QPushButton#Language_Btn:pressed{\n"
                                            "    color: white;\n"
                                            "    border:2px solid white;\n"
                                            "    border-radius: 15px;\n"
                                            "}")